language: node_js
node_js:
  - 10.15.0
  - 11.6.0

script:
  - npm run cover

jobs:
  include:
    - stage: docs
      node_js: lts/*
      script:
        - npm install -g --production coveralls codecov
        - npm run lint
        - npm run docs
        - codecov
        - cat ./coverage/lcov.info | coveralls
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
